version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: quimiport
      POSTGRES_PASSWORD: quimiport
      POSTGRES_DB: quimiport
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
